#!/usr/bin/env sh
# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

# Exit immediately if a command exits with a non-zero status.
set -e

# Set current working directory to the root of the project
cd "$(dirname "$0")/.."

echo "==> Bootstrapping application..."

# Install bundle, if not already installed
command -v bundle >/dev/null 2>&1  || {
    echo "==> Installing Ruby Bundle..."
    gem install bundler || {
        echo "Failed to install Ruby Bundle!"
        exit 1
    }
    #rbenv rehash
}

# Set bundle path to vendor/bundle, if not already set
if ! bundle config get path 2>&1 | grep -q "vendor/bundle"; then
    echo "==> Setting bundle path to 'vendor/bundle'..."
    
    bundle config set --local path 'vendor/bundle' || {
        echo "Failed to set bundle path!"
        exit 1
    }
fi

# Install gems
if [ -f "Gemfile" ]; then
    echo "==> Checking for gems..."
    
    bundle check >/dev/null 2>&1 || {
        echo "==> Installing gems..."
        
        bundle install --jobs 4 --retry 3 || {
            echo "Failed to bundle gems!"
            exit 1
        }
    }
fi

# Install yarn if it is not already installed
if ! command -v yarn >/dev/null 2>&1; then
    echo "==> Installing yarn..."
    
    npm install -g yarn || {
        echo "Failed to install yarn!"
        exit 1
    }
fi

# Install npm packages, removing existing node_modules directory if present
if [ -d "node_modules" ]; then
    echo "==> Nuking existing 'node_modules' directory..."
    rm -rf node_modules/
fi

# Check if yarn is installed, if not, install it
# if ! command -v yarn >/dev/null 2>&1; then
#     echo "==> Installing yarn..."
#     
#     npm install -g yarn || {
#         echo "Failed to install yarn!"
#         exit 1
#     }
# fi

yarn install --frozen-lockfile | grep -v warning || {
    echo "Failed to install npm dependencies."
    exit 1
}

# Build vendor assets
script/build-vendor-assets || {
    echo "Failed to build vendor assets."
    exit 1
}

echo "==> Bootstrap complete!"
exit 0