#!/usr/bin/env sh
# script/build-vendor-assets: Setup application for the first time after cloning,
#                             or set it back to the initial first unused state.

# Exit immediately if a command exits with a non-zero status.
set -e

# Set current working directory to the root of the project
cd "$(dirname "$0")/.."

# Check if node_modules exists, if not, install it
if [ ! -d "node_modules" ]; then
    echo
    echo "Application does not appear to be setup yet, run 'script/bootstrap' before running this script!"
    exit 1
fi

echo "==> Clearing out old vendor assets..."
vendor_assets_dir="assets/vendor"
node_modules_dir="node_modules"

if [ ! -d "$vendor_assets_dir" ]; then
    echo "==> Creating '${vendor_assets_dir}'"
    mkdir -p "$vendor_assets_dir" --verbose
else
    echo "==> Nuking existing '${vendor_assets_dir}' assets..."
    rm -rf "${vendor_assets_dir}"/*
fi

echo "==> Copying vendor assets..."
# jquery
cp -r $node_modules_dir/jquery/dist $vendor_assets_dir/jquery

# bootstrap and popper.js
cp -r $node_modules_dir/bootstrap/dist $vendor_assets_dir/bootstrap
cp -r $node_modules_dir/popper.js/dist $vendor_assets_dir/popper.js

# fontawesome-free
cp -r $node_modules_dir/fontawesome-free $vendor_assets_dir/fontawesome
#mv $vendor_assets_dir/fontawesome-free $vendor_assets_dir/fontawesome

# jquery-ui
cp -r $node_modules_dir/jquery-ui-dist $vendor_assets_dir/jquery-ui
#mv $vendor_assets_dir/jquery-ui-dist $vendor_assets_dir/jquery-ui

# highlight.js
mkdir -p $vendor_assets_dir/highlight.js
cp -r $node_modules_dir/highlight.js/lib $vendor_assets_dir/highlight.js/js
cp -r $node_modules_dir/highlight.js/styles $vendor_assets_dir/highlight.js/css

echo "==> App setup complete!"
exit 0