#!/usr/bin/env sh
# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

# Exit immediately if a command exits with a non-zero status.
set -e

# Set current working directory to the root of the project
cd "$(dirname "$0")/.."

echo "==> Nothing to setup."

echo "==> Setup complete!"
exit 0
