#!/usr/bin/env sh
# script/build: Test the application.

# Exit immediately if a command exits with a non-zero status.
set -e

# Set current working directory to the root of the project
cd "$(dirname "$0")/.."

script/cibuild || {
    echo "==> Failed to run 'script/cibuild'!"
    exit 1
}

echo "==> No tests to run!"

#bundle exec jekyll build
#bundle exec htmlproofer ./_site --check-html --check-sri
#bundle exec rubocop -D --config .rubocop.yml
#bundle exec script/validate-html
#gem build jekyll-theme-modernist.gemspec

echo "==> Tests complete!"
exit 0