#!/usr/bin/env sh

# Exit immediately if a command exits with a non-zero status.
set -e

# Set current working directory to the root of the project
cd "$(dirname "$0")/.."

# Set variables
sass_dir="_sass"
vendor="assets/vendor"
node_modules="node_modules"


# Install bundle, if not already installed
if ! command -v bundle >/dev/null 2>&1; then
    echo "==> Installing Ruby Bundle..."
    gem install bundler || {
        echo "Failed to install Ruby Bundle!"
        exit 1
    }
    #rbenv rehash
else
    echo "==> Bundle already installed, skipping..."
fi

# Set bundle path to vendor/bundle, if not already set
bundle config set --local path 'vendor/bundle' || {
    echo "Failed to set bundle path!"
    exit 1
}
bundle config set --local retry 3 || {
    echo "Failed to set bundle retry!"
    exit 1
}
bundle config set --local jobs 4 || {
    echo "Failed to set bundle jobs!"
    exit 1
}

# Install gems
if [ -f "Gemfile" ]; then
    echo "==> Checking for gems..."
    
    # Install gems using variables set in .bundle/config
    bundle install --gemfile Gemfile --retry 3 --jobs 4 2>&1 || {
        echo "Failed to bundle gems!"
        exit 1
    }
    # Deprecated
    # bundle check >/dev/null 2>&1 || {
    #     echo "==> Installing gems..."
    #     
    #     # Install gems using variables set in .bundle/config
    #     bundle install --gemfile Gemfile --retry 3 --jobs 4 2>&1 || {
    #         echo "Failed to bundle gems!"
    #         exit 1
    #     }
    # }
else
    echo "==> No Gemfile found, skipping gem install..."
fi

# install node modules if they are not already installed
if [ ! -d "$node_modules" ]; then
    if ! command -v npm >/dev/null 2>&1; then
        echo "==> npm is not installed..."
        exit 1
    fi
    
    # Install yarn if it is not already installed
    # if ! command -v yarn >/dev/null 2>&1; then
    #     echo "==> Installing yarn..."
    #     
    #     npm install -g yarn || {
    #         echo "Failed to install yarn!"
    #         exit 1
    #     }
    # fi
    
    # Install node modules
    npm install || {
        echo "Failed to install npm dependencies."
        exit 1
    }
    
    # Deprecated
    # if [ -f "yarn.lock" ]; then
    #     echo "==> Installing node modules with yarn..."
    #     
    #     yarn install --frozen-lockfile | grep -v warning || {
    #         echo "Failed to install npm dependencies."
    #         exit 1
    #     }
    # fi
fi

# Build site assets
scripts/build || {
    echo "Failed to build vendor assets."
    exit 1
}

echo "==> Bootstrap complete!"
exit 0
