#!/usr/bin/env sh

# Exit immediately if a command exits with a non-zero status.
set -e

# Set current working directory to the root of the project
cd "$(dirname "$0")/.."

# Set variables
sass_dir="_sass"
vendor="assets/vendor"
node_modules="node_modules"

echo "==> Checking if bundle is installed..."
# Install bundle, if not already installed
if ! command -v bundle >/dev/null 2>&1; then
    echo "==> Installing Ruby Bundle..."
    gem install bundler || {
        echo "Failed to install Ruby Bundle!"
        exit 1
    }
    #rbenv rehash
fi

echo "==> Setting bundle config..."
# Set bundle path to vendor/bundle, if not already set
bundle config set --local path 'vendor/bundle' || {
    echo "Failed to set bundle path!"
    exit 1
}
bundle config set --local retry 3 || {
    echo "Failed to set bundle retry!"
    exit 1
}
bundle config set --local jobs 4 || {
    echo "Failed to set bundle jobs!"
    exit 1
}

# Install gems using variables set in .bundle/config
bundle install --gemfile Gemfile --retry 3 --jobs 4 2>&1 || {
    echo "Failed to bundle gems!"
    exit 1
}

# Deprecated
# bundle check >/dev/null 2>&1 || {
#     echo "==> Installing gems..."
#     
#     # Install gems using variables set in .bundle/config
#     bundle install --gemfile Gemfile --retry 3 --jobs 4 2>&1 || {
#         echo "Failed to bundle gems!"
#         exit 1
#     }
# }

# Check if npm is installed
echo "==> Checking if npm is installed..."
if ! command -v npm >/dev/null 2>&1; then
    echo "==> npm is not installed..."
    exit 1
fi

# Install yarn, if not already installed
# if ! command -v yarn >/dev/null 2>&1; then
#     echo "==> installing yarn..."
#     
#     npm install -g yarn || {
#         echo "failed to install yarn!"
#         exit 1
#     }
# fi

# Install npm dependencies
echo "==> Installing npm dependencies..."
npm install || {
    echo "Failed to install npm dependencies."
    exit 1
}
# Deprecated: Install node modules with yarn
# if [ -f "yarn.lock" ]; then
#     echo "==> installing node modules with yarn..."
#     
#     yarn install --frozen-lockfile | grep -v warning || {
#         echo "failed to install npm dependencies."
#         exit 1
#     }
# fi

# Build site assets
echo "==> Running build script..."
scripts/build || {
    echo "Failed to build vendor assets."
    exit 1
}

echo "==> Bootstrap complete!"
exit 0
