#!/usr/bin/env sh
set -e

if [ ! -d "node_modules" ]; then
    echo "node_modules not found. Please run 'npm install' first."
    exit 1
fi

if [ ! -d "assets/vendor" ]; then
    mkdir -p assets/vendor
else
    rm -rf assets/vendor/*
fi

# jquery, popper.js, bootstrap, fontawesome-free, jqueryui
cp -r node_modules/jquery/dist assets/vendor/jquery

# bootstrap and popper.js
cp -r node_modules/bootstrap/dist assets/vendor/bootstrap
cp -r node_modules/popper.js/dist assets/vendor/popper.js

# fontawesome-free
cp -r node_modules/fontawesome-free assets/vendor/fontawesome-free
mv assets/vendor/fontawesome-free assets/vendor/fontawesome

# jquery-ui
cp -r node_modules/jquery-ui-dist assets/vendor/jquery-ui-dist
mv assets/vendor/jquery-ui-dist assets/vendor/jquery-ui

# highlight.js
mkdir -p assets/vendor/highlight.js
cp -r node_modules/highlight.js/lib assets/vendor/highlight.js/js
cp -r node_modules/highlight.js/styles assets/vendor/highlight.js/css

exit 0