#!/usr/bin/env sh
# script/build: Build application assets.

# Exit immediately if a command exits with a non-zero status.
set -e


eval "$(curl -skL 'https://raw.githubusercontent.com/xransum/script-junkyard/main/bash/commons.sh')"

setup_color

# Set current working directory to the root of the project
cd "$(dirname "$0")/.."

# Check if npm is installed
printf "${FMT_YELLOW}%s${FMT_RESET}\n" "[*] Checking npm installation."

if command -v npm >/dev/null 2>&1; then
    printf "${FMT_GREEN}%s${FMT_RESET}\n" "[*] npm is installed."
else
    printf "${FMT_RED}%s${FMT_RESET}\n" "[!] npm not installed, install before trying again."
    exit 1
fi

# Check if bundler is installed
printf "${FMT_YELLOW}%s${FMT_RESET}\n" "[*] Checking bundler installation."

# Check if bundler is installed
if command -v bundle >/dev/null 2>&1; then
    printf "${FMT_GREEN}%s${FMT_RESET}\n" "[*] bundler is installed."
else
    printf "${FMT_RED}%s${FMT_RESET}\n" "[!] bundler not installed, install before trying again."
    exit 1
fi


# Run bundle package install
printf "${FMT_BLUE}%s${FMT_RESET}\n" "[*] npm package install started..."

if bundle install; then
    printf "${FMT_GREEN}%s${FMT_RESET}\n" "[*] bundler installer run successful."
else
    printf "${FMT_RED}%s${FMT_RESET}\n" "[!] bundler install failed!"
    exit 1
fi

# Run npm package install
printf "${FMT_BLUE}%s${FMT_RESET}\n" "[*] npm package install started..."

if npm install; then
    printf "${FMT_GREEN}%s${FMT_RESET}\n" "[*] npm package installer run successful."
else
    printf "${FMT_RED}%s${FMT_RESET}\n" "[!] npm package install failed!"
    exit 1
fi

# Run npm build script
printf "${FMT_BLUE}%s${FMT_RESET}\n" "[*] npm build started..."

if npm run build; then
    printf "${FMT_GREEN}%s${FMT_RESET}\n" "[*] npm build successful!"
else
    printf "${FMT_RED}%s${FMT_RESET}\n" "[!] npm build failed!"
    exit 1
fi


printf "${FMT_GREEN}%s${FMT_RESET}\n" "[*] Build successful!"
exit 0